### PR TITLE
Revert "Don't force `ActionButtonUseKeyDown` to `0`"

### PR DESCRIPTION
**Pull request by dsvdmeer**
This reverts  #91. An unwanted side effect of the change made in that PR is that when clicking off a buff from your buff bar, it will remove TWO buffs: first one on mouse-down, then another on mouse-up (the one that took the place of the buff that was removed on mouse-down). Note that I only play classic, not retail. So I don't know if this a classic-only problem.

@abdes Perhaps you can find a way to fix this bug properly without completely removing your changse. But I do think that it should be possible to enable/disable this feature in settings, rather than forcing everyone to use it.

### CODE REVIEW

**Comment by abdes** [comment]
I did not see the problem on retail, and I don't play classic haha :-)
Currently too busy to play and test this, but I want to just highlight that the best practice for enabling both button-up or button-down modes is to register explicitly for the events your widgets wants or is expected to handle. This is not a TukUi specific thing, it is the general best practice.

**Comment by stva23** [comment]
Had the same Problem (WotLK), this patch fixes it. Thanks!

**Comment by dsvdmeer** [comment]
Any chance this will get merged? As it is, this added 'feature' really is still bugged (see original description), forcing me to use a forked version of TukUI.

**Comment by stva23** [comment]
Would support this, at the moment im forced to always manually merge this pull request.

**Pull request merged**
