### PR TITLE
oUF_RaidDebuffs with new aura system and class abilities

### LINKED ISSUE #190: Missing Auras
Hello.
I have had issues since DF on both my druid and other healers about missing auras on raidframes.

On druid, Lifebloom is not showing if it's talented with "Undergrowth" that make us have 2 Lifeblooms active. 
When not talented Lifebloom does show on raidframes.

Second issue is MAGIC debuffs on raidframes on some classes. On my druid and monk for example, it is not showing dispells if its magic that needs to be dispelled. This causes a big issue doing M+ keys as healers, is there a way to add magic dispells on raidframes for this season?

Big thank you in advance! I love the UI but these issues are becoming hard to have when doing high keys
Kind regards
Mcitra

### PR DESCRIPTION
**Pull request by JerichoR**
Too many changes to salvage the old one. 
Updating the dispell types.
Moving from aura scanning to UNIT_AURA payload.

Priority handling is currently missing.

Fixes #190

### CODE REVIEW

**Comment by Azilroka** [comment]
The Aura system is in all 3 clients so there shouldn't be any changes except for dispels

**Comment by JerichoR** [comment]
Ah, well. Don't know about the classic clients. But if that is there too, we should well be able to completely shift to the new one. 
Looks like I have to download the client again.

**Comment by JerichoR** [comment]
Added the classic spells too as far I could find them and removed the second implementation

**Comment by JerichoR** [comment]
The other issue is also fixed. oUF.isRetail variable was missing, so all uses of that throughout oUF failed, including oUF_AuraTrack spell whitelist. That also explains why the copy into default set worked for people. 

Will add priority handling and handling of simultaneous debuffs next.

**Comment by JerichoR** [comment]
All done. Looks good on retail, can't really test on classic.

**Pull request merged**
